version: 2
jobs:
  build:
    working_directory: ~/stern-brocot-tree
    docker:
      - image: clojure:boot-2.7.1-alpine
    environment:
      LEIN_ROOT: nbd
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: << checksum "project.clj" >>
#      - run: lein deps
      - save_cache:
          paths:
            - ~/.m2
          key: << checksum "project.clj" >>
      - run: boot pom jar target